version: '3.4'

volumes:
  app:
  data:
  dbconfig:

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - data:/data/db
      - dbconfig:/data/configdb
    ports:
      - 27017:27017

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - data:/data
    ports:
      - 6379:6379
 
  mnist-observability:
    container_name: web
    image: mnist-observability
    env_file:
      - path: ./docker.env
    build:
      context: .
      dockerfile: ./Dockerfile
    user: appuser
    volumes:
      - app:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - mongodb

  worker:
    image: mnist-observability
    deploy:
      mode: replicated
      replicas: 2
    env_file:
      - path: ./docker.env
    command: celery -A app worker --loglevel=INFO -P gevent -E
    volumes:
      - app:/app
    depends_on:
      - redis
      - mongodb
      - mnist-observability

  flower:
    container_name: flower
    image: mnist-observability
    env_file:
      - path: ./docker.env
    command: celery -A app flower
    volumes:
      - app:/app
    ports:
      - 5555:5555
    depends_on:
      - redis
      - mongodb
