version: '3.4'

volumes:
  data:

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27021:27021

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
 
  mnist-observability:
    container_name: web
    image: mnist-observability
    env_file:
      - path: ./docker.env
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
      - MNIST_DATASET_DIR=${MNIST_DATASET_DIR}
      - CHECKPOINT_DIR=${CHECKPOINT_DIR}
      - LOG_DIR=${LOG_DIR}
    build:
      context: .
      dockerfile: ./Dockerfile
    user: appuser
    volumes:
      - data:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - mongodb
      - worker

  worker:
    container_name: worker
    image: mnist-observability
    env_file:
      - path: ./docker.env
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
      - MNIST_DATASET_DIR=${MNIST_DATASET_DIR}
      - CHECKPOINT_DIR=${CHECKPOINT_DIR}
      - LOG_DIR=${LOG_DIR}
    command: celery -A app worker --loglevel=INFO -P gevent
    volumes:
      - data:/app
    depends_on:
      - redis
      - mongodb

  flower:
    container_name: flower
    image: mnist-observability
    env_file:
      - path: ./docker.env
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
      - MNIST_DATASET_DIR=${MNIST_DATASET_DIR}
      - CHECKPOINT_DIR=${CHECKPOINT_DIR}
      - LOG_DIR=${LOG_DIR}
    command: celery -A app flower
    volumes:
      - data:/app
    ports:
      - 5555:5555
    depends_on:
      - redis
      - mongodb
      - worker
